### PR TITLE
Fix procfetch#124: use --prefix instead of -C

### PR DESCRIPTION
**Pull request by youpong**
## Description

call the `configure` with `--prefix` instead of -C.

## Related Issue
* TanmayPatil105/procfetch#124

### CODE REVIEW

**Comment by TanmayPatil105** [comment]
This will work.
But we need to add uninstall function too!
Once installed, we won't be able to uninstall it.

**Comment by youpong** [comment]
I tried it and was able to uninstall it.
After uninstalling, keg disappeared from Cellar and the 2 links to it was also removed.

**Comment by TanmayPatil105** [comment]
You must have done it manually?
I meant by using `brew uninstall procfetch`!
Currently, the script has
```ruby
bin.install "src/procfetch"
```
So, whenever do `brew uninstall procfetch`, It removes the binary but not the ascii arts.

**Comment by youpong** [comment]
Yes. I have done it by using `brew`.

After merging this pull request, bellow line will be removed.
```ruby
bin.install "src/procfetch"
```

**Pull request merged**
